### ISSUE TITLE
Redundant white color around the logo - Main page

### ISSUE THREAD

**Issue by V3rochka** [bsidestlv/2020.bsidestlv.com#57]
![image](https://user-images.githubusercontent.com/9990629/85850954-7b5f5e80-b7b6-11ea-813f-b08a47145c84.png)

**Comment by omercnet** [comment]
@xFreed0m can you please work with Oded to get a new logo?

**Comment by omercnet** [comment]
@V3rochka if I give you the original can you make a better version?

**Comment by xFreed0m** [comment]
update version @omercnet 
https://drive.google.com/file/d/1f2zzgjzOLr2Va-fKaWi02H_7OLCeFfWV/view?usp=sharing
